Feature/profile page
tinysoft-ph/baiji-ui pull request #11
Opened 2017-03-31 22:53 UTC by zerojuan

## Before
- No profile page

## Now
- Basic profile page implementation

2017-04-04 10:50 UTC, janejanejane requested changes

2017-04-04 10:50 UTC, janejanejane commented on app/containers/ProfilePage/constants.js
> +export const PROFILE_LOAD_SUCCESS = 'baiji/ProfilePage/PROFILE_LOADED';
Shouldn't this be 'baiji/ProfilePage/PROFILE_LOADED_SUCCESS' instead?

2017-04-04 10:50 UTC, janejanejane commented on app/containers/ProfilePage/index.js
> +  profile: PropTypes.object,
Can we use PropTypes.shape instead of PropTypes.object?

2017-04-05 03:32 UTC, zerojuan commented on app/containers/ProfilePage/index.js
> +  profile: PropTypes.object,
We can but I'm not sure what the shape of that object will be. So this is just a placeholder.

2017-04-05 10:27 UTC, merged